cmake_minimum_required(VERSION 3.25)

# ---------------------------------------------------------------------------
# adecc Stage-0 bootstrap
#
# Run from a C++Builder Developer Command Prompt:
#
#    cmake -P bootstrap/Bootstrap.cmake
#
# No compiler invocation is required. CMake itself downloads, verifies and
# extracts the packages described by Cache/thirdparty.lock.
# ---------------------------------------------------------------------------

get_filename_component(
   ADECC_REPOSITORY_ROOT
   "${CMAKE_CURRENT_LIST_DIR}/.."
   ABSOLUTE
)

set(ADECC_CACHE_ROOT      "${ADECC_REPOSITORY_ROOT}/Cache")
set(ADECC_ARCHIVE_ROOT    "${ADECC_CACHE_ROOT}/archives")
set(ADECC_STATE_ROOT      "${ADECC_CACHE_ROOT}/bootstrap-state")
set(ADECC_THIRDPARTY_ROOT "${ADECC_REPOSITORY_ROOT}/ThirdParty")

include("${CMAKE_CURRENT_LIST_DIR}/BootstrapConfig.cmake")

if(ADECC_PACKAGE_REPOSITORY MATCHES "REPLACE-ME")
   message(FATAL_ERROR
      "bootstrap/BootstrapConfig.cmake still contains REPLACE-ME. "
      "Set ADECC_PACKAGE_REPOSITORY once before distributing the project."
   )
endif()

file(MAKE_DIRECTORY
   "${ADECC_CACHE_ROOT}"
   "${ADECC_ARCHIVE_ROOT}"
   "${ADECC_STATE_ROOT}"
   "${ADECC_THIRDPARTY_ROOT}"
)

# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

if("$ENV{BDS}" STREQUAL "")
   message(FATAL_ERROR
      "BDS is not set. Start a C++Builder Developer Command Prompt and run "
      "the bootstrap from there."
   )
endif()

file(TO_CMAKE_PATH "$ENV{BDS}" ADECC_BDS_ROOT)
file(TO_CMAKE_PATH "${CMAKE_COMMAND}" ADECC_CMAKE_EXECUTABLE)
get_filename_component(ADECC_CMAKE_BIN_DIR "${ADECC_CMAKE_EXECUTABLE}" DIRECTORY)

set(ADECC_BCC64X_EXECUTABLE "${ADECC_BDS_ROOT}/bin64/bcc64x.exe")
if(NOT EXISTS "${ADECC_BCC64X_EXECUTABLE}")
   find_program(
      ADECC_BCC64X_EXECUTABLE
      NAMES bcc64x.exe bcc64x
      HINTS
         "${ADECC_BDS_ROOT}/bin64"
         "${ADECC_BDS_ROOT}/bin"
      NO_CACHE
   )
endif()

if(NOT ADECC_BCC64X_EXECUTABLE OR NOT EXISTS "${ADECC_BCC64X_EXECUTABLE}")
   message(FATAL_ERROR
      "bcc64x was not found below BDS or on PATH. BDS=${ADECC_BDS_ROOT}"
   )
endif()
file(TO_CMAKE_PATH "${ADECC_BCC64X_EXECUTABLE}" ADECC_BCC64X_EXECUTABLE)

find_program(
   ADECC_NINJA_EXECUTABLE
   NAMES ninja.exe ninja
   HINTS
      "${ADECC_CMAKE_BIN_DIR}"
      "${ADECC_BDS_ROOT}/bin64"
      "${ADECC_BDS_ROOT}/bin"
   NO_CACHE
)
if(ADECC_NINJA_EXECUTABLE)
   file(TO_CMAKE_PATH "${ADECC_NINJA_EXECUTABLE}" ADECC_NINJA_EXECUTABLE)
else()
   set(ADECC_NINJA_EXECUTABLE "")
endif()

execute_process(
   COMMAND "${ADECC_BCC64X_EXECUTABLE}" --version
   RESULT_VARIABLE _adecc_bcc64x_result
   OUTPUT_VARIABLE _adecc_bcc64x_stdout
   ERROR_VARIABLE  _adecc_bcc64x_stderr
)
set(ADECC_BCC64X_VERSION_TEXT "${_adecc_bcc64x_stdout} ${_adecc_bcc64x_stderr}")
string(REPLACE "\r" "" ADECC_BCC64X_VERSION_TEXT "${ADECC_BCC64X_VERSION_TEXT}")
string(REPLACE "\n" " | " ADECC_BCC64X_VERSION_TEXT "${ADECC_BCC64X_VERSION_TEXT}")
string(STRIP "${ADECC_BCC64X_VERSION_TEXT}" ADECC_BCC64X_VERSION_TEXT)

function(_adecc_append_set theFile theName theValue)
   set(_value "${theValue}")
   string(REPLACE "\\" "/" _value "${_value}")
   string(REPLACE "\"" "\\\"" _value "${_value}")
   file(APPEND "${theFile}" "set(${theName} \"${_value}\")\n")
endfunction()

set(ADECC_TOOLS_FILE "${ADECC_CACHE_ROOT}/BootstrapTools.cmake")
file(WRITE "${ADECC_TOOLS_FILE}"
"# Generated by bootstrap/Bootstrap.cmake - do not edit.\n"
"# Machine-local tool evidence.\n\n"
)
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_REPOSITORY_ROOT "${ADECC_REPOSITORY_ROOT}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_BDS_ROOT "${ADECC_BDS_ROOT}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_BCC64X_EXECUTABLE "${ADECC_BCC64X_EXECUTABLE}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_BCC64X_VERSION_TEXT "${ADECC_BCC64X_VERSION_TEXT}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_CMAKE_EXECUTABLE "${ADECC_CMAKE_EXECUTABLE}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_CMAKE_VERSION "${CMAKE_VERSION}")
_adecc_append_set("${ADECC_TOOLS_FILE}" ADECC_NINJA_EXECUTABLE "${ADECC_NINJA_EXECUTABLE}")

message(STATUS "Repository root : ${ADECC_REPOSITORY_ROOT}")
message(STATUS "BDS root        : ${ADECC_BDS_ROOT}")
message(STATUS "bcc64x          : ${ADECC_BCC64X_EXECUTABLE}")
message(STATUS "CMake           : ${ADECC_CMAKE_EXECUTABLE}")
message(STATUS "CMake version   : ${CMAKE_VERSION}")
if(ADECC_NINJA_EXECUTABLE)
   message(STATUS "Ninja           : ${ADECC_NINJA_EXECUTABLE}")
else()
   message(WARNING "Ninja was not found. Bootstrap can continue, but project builds may need it.")
endif()

# ---------------------------------------------------------------------------
# Lock file
# ---------------------------------------------------------------------------

set(ADECC_LOCK_FILE "${ADECC_CACHE_ROOT}/thirdparty.lock")
set(ADECC_LOCK_XML  "${ADECC_CACHE_ROOT}/thirdparty.lock.xml")

if(NOT EXISTS "${ADECC_LOCK_FILE}")
   message(FATAL_ERROR "Missing ${ADECC_LOCK_FILE}")
endif()

if(NOT EXISTS "${ADECC_LOCK_XML}")
   message(WARNING
      "thirdparty.lock.xml is not present beside thirdparty.lock. "
      "The bootstrap uses the text lock, but both files should normally be committed."
   )
endif()

file(STRINGS "${ADECC_LOCK_FILE}" _adecc_lock_lines ENCODING UTF-8)

list(FIND _adecc_lock_lines "StackBuilder-ThirdParty-Lock|2" _adecc_header_index)
if(_adecc_header_index EQUAL -1)
   message(FATAL_ERROR
      "Unsupported thirdparty.lock. Expected StackBuilder-ThirdParty-Lock|2."
   )
endif()

set(_adecc_lock_toolchain "")
foreach(_line IN LISTS _adecc_lock_lines)
   if(_line MATCHES "^toolchain\\|")
      string(REPLACE "|" ";" _fields "${_line}")
      list(LENGTH _fields _field_count)
      if(_field_count EQUAL 2)
         list(GET _fields 1 _adecc_lock_toolchain)
      endif()
   endif()
endforeach()

if(NOT _adecc_lock_toolchain STREQUAL ADECC_REQUIRED_TOOLCHAIN)
   message(FATAL_ERROR
      "thirdparty.lock toolchain '${_adecc_lock_toolchain}' does not match "
      "required toolchain '${ADECC_REQUIRED_TOOLCHAIN}'."
   )
endif()

# ---------------------------------------------------------------------------
# Generated package map used by Cache/cmake/ThirdParty.cmake
# ---------------------------------------------------------------------------

set(ADECC_PACKAGES_FILE "${ADECC_CACHE_ROOT}/ThirdPartyPackages.cmake")
file(WRITE "${ADECC_PACKAGES_FILE}"
"# Generated by bootstrap/Bootstrap.cmake from Cache/thirdparty.lock.\n"
"# Relocatable: ADECC_REPOSITORY_ROOT is supplied by Cache/cmake/ThirdParty.cmake.\n\n"
"set(ADECC_THIRDPARTY_PACKAGE_ROOTS)\n"
)

function(_adecc_write_package_map theName theVersion theRelease theArchive theSha256)
   string(MAKE_C_IDENTIFIER "${theName}" _id)
   string(TOUPPER "${_id}" _id)

   file(APPEND "${ADECC_PACKAGES_FILE}"
      "\n"
      "set(ADECC_TP_${_id}_VERSION \"${theVersion}\")\n"
      "set(ADECC_TP_${_id}_RELEASE \"${theRelease}\")\n"
      "set(ADECC_TP_${_id}_ARCHIVE \"${theArchive}\")\n"
      "set(ADECC_TP_${_id}_SHA256 \"${theSha256}\")\n"
      "set(ADECC_TP_${_id}_ROOT \"\${ADECC_REPOSITORY_ROOT}/ThirdParty/${theName}/${theVersion}\")\n"
      "list(APPEND ADECC_THIRDPARTY_PACKAGE_ROOTS \"\${ADECC_TP_${_id}_ROOT}\")\n"
   )
endfunction()

function(_adecc_verify_cached_archive theArchive theExpectedSize theExpectedSha theResultVar)
   if(NOT EXISTS "${theArchive}")
      set(${theResultVar} FALSE PARENT_SCOPE)
      return()
   endif()

   file(SIZE "${theArchive}" _actual_size)
   if(NOT "${_actual_size}" STREQUAL "${theExpectedSize}")
      set(${theResultVar} FALSE PARENT_SCOPE)
      return()
   endif()

   file(SHA256 "${theArchive}" _actual_sha)
   string(TOLOWER "${_actual_sha}" _actual_sha)
   string(TOLOWER "${theExpectedSha}" _expected_sha)
   if(NOT _actual_sha STREQUAL _expected_sha)
      set(${theResultVar} FALSE PARENT_SCOPE)
      return()
   endif()

   set(${theResultVar} TRUE PARENT_SCOPE)
endfunction()

set(_adecc_package_count 0)

foreach(_line IN LISTS _adecc_lock_lines)
   if(NOT _line MATCHES "^package\\|")
      continue()
   endif()

   string(REPLACE "|" ";" _fields "${_line}")
   list(LENGTH _fields _field_count)
   if(NOT _field_count EQUAL 7)
      message(FATAL_ERROR "Malformed package line in thirdparty.lock: ${_line}")
   endif()

   list(GET _fields 1 _name)
   list(GET _fields 2 _version)
   list(GET _fields 3 _release)
   list(GET _fields 4 _archive_rel)
   list(GET _fields 5 _size)
   list(GET _fields 6 _sha256)

   math(EXPR _adecc_package_count "${_adecc_package_count} + 1")

   get_filename_component(_archive_name "${_archive_rel}" NAME)
   set(_archive_file "${ADECC_ARCHIVE_ROOT}/${_archive_name}")
   set(_archive_part "${_archive_file}.part")
   set(_package_root "${ADECC_THIRDPARTY_ROOT}/${_name}")
   set(_version_root "${_package_root}/${_version}")
   set(_state_file "${ADECC_STATE_ROOT}/${_name}.sha256")

   _adecc_write_package_map(
      "${_name}" "${_version}" "${_release}" "${_archive_name}" "${_sha256}"
   )

   _adecc_verify_cached_archive(
      "${_archive_file}" "${_size}" "${_sha256}" _archive_ok
   )

   if(NOT _archive_ok)
      file(REMOVE "${_archive_file}" "${_archive_part}")

      string(REGEX REPLACE "/+$" "" _repository "${ADECC_PACKAGE_REPOSITORY}")
      string(REGEX REPLACE "\\.git$" "" _repository "${_repository}")
      set(_url "${_repository}/releases/download/${_release}/${_archive_name}")

      message(STATUS "[DOWNLOAD] ${_name} ${_version}")
      file(
         DOWNLOAD
         "${_url}"
         "${_archive_part}"
         EXPECTED_HASH "SHA256=${_sha256}"
         TLS_VERIFY ON
         SHOW_PROGRESS
         STATUS _download_status
      )

      list(GET _download_status 0 _download_code)
      list(GET _download_status 1 _download_text)
      if(NOT _download_code EQUAL 0)
         file(REMOVE "${_archive_part}")
         message(FATAL_ERROR
            "Download failed for ${_name} ${_version}: ${_download_text}\n${_url}"
         )
      endif()

      file(SIZE "${_archive_part}" _download_size)
      if(NOT "${_download_size}" STREQUAL "${_size}")
         file(REMOVE "${_archive_part}")
         message(FATAL_ERROR
            "Size mismatch for ${_name} ${_version}: "
            "expected ${_size}, got ${_download_size}"
         )
      endif()

      file(RENAME "${_archive_part}" "${_archive_file}")
   else()
      message(STATUS "[CACHE]    ${_name} ${_version}")
   endif()

   set(_state_sha "")
   if(EXISTS "${_state_file}")
      file(READ "${_state_file}" _state_sha)
      string(STRIP "${_state_sha}" _state_sha)
   endif()
   string(TOLOWER "${_state_sha}" _state_sha)
   string(TOLOWER "${_sha256}" _expected_state_sha)

   if(_state_sha STREQUAL _expected_state_sha AND EXISTS "${_version_root}")
      message(STATUS "[READY]    ${_name} ${_version}")
   else()
      message(STATUS "[EXTRACT]  ${_name} ${_version}")

      # The StackBuilder archives are relative to the library root.  Therefore
      # the archive is extracted into ThirdParty/<package>, not directly into
      # ThirdParty/<package>/<version>.  This also preserves siblings such as
      # boost/bcc64x-native-clang.
      file(REMOVE_RECURSE "${_package_root}")
      file(MAKE_DIRECTORY "${_package_root}")
      file(
         ARCHIVE_EXTRACT
         INPUT "${_archive_file}"
         DESTINATION "${_package_root}"
      )

      if(NOT EXISTS "${_version_root}")
         message(FATAL_ERROR
            "Archive ${_archive_name} did not create expected directory "
            "${_version_root}"
         )
      endif()

      file(WRITE "${_state_file}" "${_sha256}\n")
   endif()
endforeach()

if(_adecc_package_count EQUAL 0)
   message(FATAL_ERROR "thirdparty.lock does not contain any package lines.")
endif()

message(STATUS "Bootstrap complete: ${_adecc_package_count} packages")
message(STATUS "Tool paths       : ${ADECC_TOOLS_FILE}")
message(STATUS "Package map      : ${ADECC_PACKAGES_FILE}")
message(STATUS "ThirdParty root  : ${ADECC_THIRDPARTY_ROOT}")
