// SPDX-FileCopyrightText: 2021 - 2026 adecc Systemhaus GmbH
// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

/**
\file database_test_dialects.h
\brief Database-dialect fixtures used to exercise the same logical tests on SQL Server, PostgreSQL, and SQLite.

\details
Centralizes the small pieces of SQL syntax that necessarily differ between supported test databases,
including identity columns, generated columns, and year extraction. Keeping these differences explicit
allows the higher-level database tests to verify one logical contract across multiple physical database
systems.

\par Architectural background
This header follows the architecture described by Volker Hillmann in
*Rethinking C++ (C++ neu denken)*, especially:
- "Tests as Architectural Proof".
- "Migration as an Architecture Test".
- "Database as a Relational Source and Sink".
- "Why This Is Not a Classical ORM: SQL Remains Visible".

\see ../ARCHITECTURE.md#migration-as-an-architecture-test

\version 1.0
\date 26.09.2026
\author Volker Hillmann (adecc Systemhaus GmbH)

\copyright Copyright © 2021 - 2026 adecc Systemhaus GmbH

\licenseblock{LicenseRef-PolyForm-Noncommercial-1.0.0}
This file is licensed under the PolyForm Noncommercial License 1.0.0.
Use, modification, and distribution are permitted only as defined by that license.
The complete and controlling terms are available at
https://polyformproject.org/licenses/noncommercial/1.0.0/.
Any use not permitted by that license requires separate permission or a separate
license from adecc Systemhaus GmbH.
\endlicenseblock

*/

#pragma once

#include <stdexcept>
#include <string_view>

namespace adecc::test {

enum class database_dialect {
   sql_server,
   postgresql,
   sqlite
   };

[[nodiscard]] constexpr std::string_view DialectName(database_dialect const aDialect) {
   switch(aDialect) {
      case database_dialect::sql_server: return "SQL Server";
      case database_dialect::postgresql: return "PostgreSQL";
      case database_dialect::sqlite:     return "SQLite";
      }

   throw std::logic_error { "unknown database test dialect" };
   }

[[nodiscard]] constexpr std::string_view SimpleTestTableDdl(database_dialect const aDialect) {
   switch(aDialect) {
      case database_dialect::sql_server:
         return
            "IF OBJECT_ID('TestDbNeu', 'U') IS NOT NULL DROP TABLE TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id int IDENTITY(1,1) NOT NULL PRIMARY KEY,"
            "Name nvarchar(100) NOT NULL,"
            "Kommentar nvarchar(200) NULL,"
            "Wert int NOT NULL"
            ")";

      case database_dialect::postgresql:
         return
            "DROP TABLE IF EXISTS TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "Name varchar(100) NOT NULL,"
            "Kommentar varchar(200) NULL,"
            "Wert integer NOT NULL"
            ")";

      case database_dialect::sqlite:
         return
            "DROP TABLE IF EXISTS TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "Name TEXT NOT NULL,"
            "Kommentar TEXT NULL,"
            "Wert INTEGER NOT NULL"
            ")";
      }

   throw std::logic_error { "unknown database test dialect" };
   }

[[nodiscard]] constexpr std::string_view PersistentTestTableDdl(database_dialect const aDialect) {
   switch(aDialect) {
      case database_dialect::sql_server:
         return
            "IF OBJECT_ID('TestDbNeu', 'U') IS NOT NULL DROP TABLE TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id int IDENTITY(1,1) NOT NULL PRIMARY KEY,"
            "Name nvarchar(100) NOT NULL,"
            "Kommentar nvarchar(200) NULL,"
            "Wert int NOT NULL,"
            "WertDoppelt AS (Wert * 2)"
            ")";

      case database_dialect::postgresql:
         return
            "DROP TABLE IF EXISTS TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "Name varchar(100) NOT NULL,"
            "Kommentar varchar(200) NULL,"
            "Wert integer NOT NULL,"
            "WertDoppelt integer GENERATED ALWAYS AS (Wert * 2) STORED"
            ")";

      case database_dialect::sqlite:
         return
            "DROP TABLE IF EXISTS TestDbNeu; "
            "CREATE TABLE TestDbNeu ("
            "Id INTEGER PRIMARY KEY AUTOINCREMENT,"
            "Name TEXT NOT NULL,"
            "Kommentar TEXT NULL,"
            "Wert INTEGER NOT NULL,"
            "WertDoppelt INTEGER GENERATED ALWAYS AS (Wert * 2) STORED"
            ")";
      }

   throw std::logic_error { "unknown database test dialect" };
   }

[[nodiscard]] constexpr std::string_view YearFilterExpression(database_dialect const aDialect) {
   switch(aDialect) {
      case database_dialect::sql_server:
         return "YEAR(Booking_Date) = :ByYear";
      case database_dialect::postgresql:
         return "EXTRACT(YEAR FROM Booking_Date) = :ByYear";
      case database_dialect::sqlite:
         return "CAST(strftime('%Y', Booking_Date) AS INTEGER) = :ByYear";
      }

   throw std::logic_error { "unknown database test dialect" };
   }

} // namespace adecc::test
