// SPDX-FileCopyrightText: 2021 - 2026 adecc Systemhaus GmbH
// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

/**
\file extented_test_create.h
\brief Database schema creation helpers for the extended accounting integration tests.

\details
Creates the relational structures used by the accounting scenarios for SQL Server, PostgreSQL, and SQLite
while preserving one logical model. Dialect-specific identity, boolean, text, and primary-key syntax is
isolated here so that the remaining tests stay database-neutral.

\par Architectural background
This header follows the architecture described by Volker Hillmann in
*Rethinking C++ (C++ neu denken)*, especially:
- "Tests as Architectural Proof".
- "Migration as an Architecture Test".
- "Database as a Relational Source and Sink".
- "Why This Is Not a Classical ORM: SQL Remains Visible".

\see ../ARCHITECTURE.md#migration-as-an-architecture-test

\version 1.0
\date 26.09.2026
\author Volker Hillmann (adecc Systemhaus GmbH)

\copyright Copyright © 2021 - 2026 adecc Systemhaus GmbH

\licenseblock{LicenseRef-PolyForm-Noncommercial-1.0.0}
This file is licensed under the PolyForm Noncommercial License 1.0.0.
Use, modification, and distribution are permitted only as defined by that license.
The complete and controlling terms are available at
https://polyformproject.org/licenses/noncommercial/1.0.0/.
Any use not permitted by that license requires separate permission or a separate
license from adecc Systemhaus GmbH.
\endlicenseblock

*/

#pragma once

#include "database.h"
#include "database_test_dialects.h"
#include <iostream>
#include <format>
#include <string_view>
#include <string>
#include <print>

namespace extented_test {

   template <adecc::db::logical_database_type app_db>
   void CreateTables(app_db& db, std::ostream& os,
                     adecc::test::database_dialect const aDialect = adecc::test::database_dialect::sql_server) {
      using adecc::test::database_dialect;

      if(aDialect == database_dialect::sqlite)
         db.ExecuteCommand("PRAGMA foreign_keys = ON;");

      db.ExecuteCommand(
         "DROP TABLE IF EXISTS Test_Posting;"
         "DROP TABLE IF EXISTS Test_TaxClass;"
         "DROP TABLE IF EXISTS Test_NominalAcct;"
         "DROP TABLE IF EXISTS Test_Account;"
         "DROP TABLE IF EXISTS Test_AccountClass;"
         "DROP TABLE IF EXISTS Test_AccountType;"
         "DROP TABLE IF EXISTS Test_AddressType;");

      auto const Identity = [aDialect](std::string_view const svName) {
         if(aDialect == database_dialect::sql_server)
            return std::format("{} INTEGER IDENTITY(1,1) NOT NULL", svName);
         if(aDialect == database_dialect::postgresql)
            return std::format("{} INTEGER GENERATED BY DEFAULT AS IDENTITY", svName);
         return std::format("{} INTEGER PRIMARY KEY AUTOINCREMENT", svName);
         };

      auto const PrimaryKey = [aDialect](std::string_view const svConstraint,
                                         std::string_view const svColumn) {
         if(aDialect == database_dialect::sqlite)
            return std::string{};
         return std::format("CONSTRAINT {} PRIMARY KEY{} ({}),",
                            svConstraint,
                            aDialect == database_dialect::sql_server ? " CLUSTERED" : "",
                            svColumn);
         };

      auto const strLargeText =
         aDialect == database_dialect::sql_server ? "VARCHAR(MAX)" : "TEXT";

      auto const strBoolType =
         aDialect == database_dialect::postgresql ? "BOOLEAN" :
         aDialect == database_dialect::sqlite ? "INTEGER" : "SMALLINT";

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_AddressType ("
         "ID INTEGER NOT NULL,"
         "Denotation VARCHAR(50) NOT NULL,"
         "Abbreviation VARCHAR(10) NOT NULL,"
         "Description {} NULL,"
         "CONSTRAINT pk_Test_AddressType PRIMARY KEY{} (ID),"
         "CONSTRAINT uk_Test_AddressType_Denotation UNIQUE (Denotation),"
         "CONSTRAINT uk_Test_AddressType_Abbreviation UNIQUE (Abbreviation)"
         ")",
         strLargeText,
         aDialect == database_dialect::sql_server ? " CLUSTERED" : ""));
      std::println(os, "Table Test_AddressType was recreated.");

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_AccountType ("
         "{},"
         "Denotation VARCHAR(100) NOT NULL,"
         "Abbreviation VARCHAR(10) NOT NULL,"
         "Description {} NULL,"
         "{}"
         "CONSTRAINT uk_Test_AccountType_Denotation UNIQUE (Denotation)"
         ")",
         Identity("ID"), strLargeText,
         PrimaryKey("pk_Test_AccountType", "ID")));
      std::println(os, "Table Test_AccountType was recreated.");

      std::string strNaturalSideCheck;
      if(aDialect == database_dialect::postgresql)
         strNaturalSideCheck =
            "CONSTRAINT ck_Test_AccountClass_NaturalSide CHECK ("
            "(Natural_Debit AND NOT Natural_Credit) OR "
            "(NOT Natural_Debit AND Natural_Credit) OR "
            "(NOT Natural_Debit AND NOT Natural_Credit))";
      else
         strNaturalSideCheck =
            "CONSTRAINT ck_Test_AccountClass_NaturalSide CHECK ("
            "(Natural_Debit = 1 AND Natural_Credit = 0) OR "
            "(Natural_Debit = 0 AND Natural_Credit = 1) OR "
            "(Natural_Debit = 0 AND Natural_Credit = 0))";

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_AccountClass ("
         "{},"
         "Denotation VARCHAR(100) NOT NULL,"
         "Description {} NULL,"
         "Type_Code VARCHAR(30) NOT NULL,"
         "Balance_Side VARCHAR(10) NOT NULL,"
         "Pnl_Relevant {} NOT NULL,"
         "Balance_Sheet_Relevant {} NOT NULL,"
         "Natural_Debit {} NOT NULL,"
         "Natural_Credit {} NOT NULL,"
         "Sort_Order INTEGER NOT NULL,"
         "{}"
         "CONSTRAINT uk_Test_AccountClass_Denotation UNIQUE (Denotation),"
         "CONSTRAINT ck_Test_AccountClass_BalanceSide CHECK(Balance_Side IN ('Debit','Credit','None')),"
         "{}"
         ")",
         Identity("ID"), strLargeText,
         strBoolType, strBoolType, strBoolType, strBoolType,
         PrimaryKey("pk_Test_AccountClass", "ID"),
         strNaturalSideCheck));
      std::println(os, "Table Test_AccountClass was recreated.");

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_Account ("
         "{},"
         "Account_No INTEGER NOT NULL,"
         "Denotation VARCHAR(100) NOT NULL,"
         "Account_Type INTEGER NOT NULL,"
         "{}"
         "CONSTRAINT uk_Test_Account_No UNIQUE (Account_No),"
         "CONSTRAINT uk_Test_Account_Description UNIQUE (Denotation),"
         "CONSTRAINT fk_Test_Account_AcctType FOREIGN KEY (Account_Type) REFERENCES Test_AccountType(ID)"
         ")",
         Identity("ID"),
         PrimaryKey("pk_Test_Account", "ID")));
      std::println(os, "Table Test_Account was recreated.");

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_NominalAcct ("
         "ID INTEGER NOT NULL,"
         "Account_Class INTEGER NOT NULL,"
         "Currency CHAR(3) NOT NULL DEFAULT 'EUR',"
         "IsActive {} NOT NULL DEFAULT {},"
         "Description {} NULL,"
         "CONSTRAINT pk_Test_NominalAcct PRIMARY KEY{} (ID),"
         "CONSTRAINT fk_Test_NominalAcct_Account FOREIGN KEY (ID) REFERENCES Test_Account(ID),"
         "CONSTRAINT fk_Test_NominalAcct_AcctClass FOREIGN KEY (Account_Class) REFERENCES Test_AccountClass(ID)"
         ")",
         strBoolType,
         aDialect == database_dialect::postgresql ? "TRUE" : "1",
         strLargeText,
         aDialect == database_dialect::sql_server ? " CLUSTERED" : ""));
      std::println(os, "Table Test_NominalAcct was recreated.");

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_TaxClass ("
         "{},"
         "Tax_Class VARCHAR(15) NOT NULL,"
         "Description VARCHAR(50) NOT NULL,"
         "Tax_Percent DECIMAL(5,2) NOT NULL,"
         "Tax_Acct_Debit INTEGER NULL,"
         "Tax_Acct_Credit INTEGER NULL,"
         "Eligible_for_Tax {} NOT NULL,"
         "Subject_to_Tax {} NOT NULL,"
         "{}"
         "CONSTRAINT uk_Test_TaxClass_Class UNIQUE (Tax_Class),"
         "CONSTRAINT uk_Test_TaxClass_Description UNIQUE (Description),"
         "CONSTRAINT fk_Test_TaxClass_Tax_Acct_Debit FOREIGN KEY (Tax_Acct_Debit) REFERENCES Test_Account(ID),"
         "CONSTRAINT fk_Test_TaxClass_Tax_Acct_Credit FOREIGN KEY (Tax_Acct_Credit) REFERENCES Test_Account(ID)"
         ")",
         Identity("ID"), strBoolType, strBoolType,
         PrimaryKey("pk_Test_TaxClass", "ID")));
      std::println(os, "Table Test_TaxClass was recreated.");

      db.ExecuteCommand(std::format(
         "CREATE TABLE Test_Posting ("
         "{},"
         "Booking_Date DATE NOT NULL,"
         "Booking_No VARCHAR(30) NOT NULL,"
         "Debit_Acct_ID INTEGER NOT NULL,"
         "Credit_Acct_ID INTEGER NOT NULL,"
         "Amount DECIMAL(15,2) NOT NULL,"
         "Tax_Class INTEGER NOT NULL,"
         "Posting_Text VARCHAR(255) NOT NULL,"
         "{}"
         "CONSTRAINT fk_Test_Booking_Debit_Acct FOREIGN KEY (Debit_Acct_ID) REFERENCES Test_Account(ID),"
         "CONSTRAINT fk_Test_Booking_Credit_Acct FOREIGN KEY (Credit_Acct_ID) REFERENCES Test_Account(ID),"
         "CONSTRAINT fk_Test_Booking_Tax_Class FOREIGN KEY (Tax_Class) REFERENCES Test_TaxClass(ID),"
         "CONSTRAINT ck_Test_Booking_Different_Acct CHECK(Debit_Acct_ID <> Credit_Acct_ID)"
         ")",
         Identity("ID"),
         PrimaryKey("pk_Test_Booking", "ID")));
      std::println(os, "Table Test_Posting was recreated.");
      std::println(os);
      }

} // namespace extented_test