// SPDX-FileCopyrightText: 2021 - 2026 adecc Systemhaus GmbH
// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0

/**
\file persistence_test.h
\brief Integration tests for PersistentSystemData metadata, generated identities, updates, and read-only fields.

\details
Verifies generated SQL, parameter roles, identity propagation, metadata-driven inserts and updates, and
database-generated read-only values. The tests demonstrate that persistence behavior follows the typed
metadata rather than duplicated mapping code.

\par Architectural background
This header follows the architecture described by Volker Hillmann in
*Rethinking C++ (C++ neu denken)*, especially:
- "PersistentSystemData as an Extension of SystemData".
- "Ranges, Lazy Processing, and Materialization".
- "Tests as Architectural Proof".
- "Migration as an Architecture Test".

\see ../ARCHITECTURE.md#persistentsystemdata

\version 1.0
\date 26.09.2026
\author Volker Hillmann (adecc Systemhaus GmbH)

\copyright Copyright © 2021 - 2026 adecc Systemhaus GmbH

\licenseblock{LicenseRef-PolyForm-Noncommercial-1.0.0}
This file is licensed under the PolyForm Noncommercial License 1.0.0.
Use, modification, and distribution are permitted only as defined by that license.
The complete and controlling terms are available at
https://polyformproject.org/licenses/noncommercial/1.0.0/.
Any use not permitted by that license requires separate permission or a separate
license from adecc Systemhaus GmbH.
\endlicenseblock

*/

#pragma once

#include "database.h"
#include "system_data_persistent.h"
#include "database_test_dialects.h"
#include "stream_tools.h"

#include <string>
#include <string_view>
#include <optional>
#include <algorithm>
#include <numeric>

#include <exception>

using testdbneu_list = adecc::defined_type_list<
   int,                  // Id
   std::string,          // Name
   std::string,          // Comment
   int,                  // Value
   std::optional<int>    // ValueDoubled, computed read-only field
   >;


inline adecc::vecCaptions<adecc::AnsiStreamPolicy> testdbneu_captions = {
	 { "Id",            80, adecc::EAlignmentType::right },
	 { "Name",         180, adecc::EAlignmentType::left  },
	 { "Comment",       250, adecc::EAlignmentType::left  },
	 { "Value",         100, adecc::EAlignmentType::right },
	 { "ValueDoubled",  120, adecc::EAlignmentType::right }
  };


struct TestDbNeuMetaData {
   static constexpr std::string_view svTableName = "TestDbNeu";

   static constexpr std::array<std::string_view, 5> arrAttributeNames {
		  "Id", "Name", "Kommentar", "Wert", "WertDoppelt"
	  };

   static constexpr std::array<std::size_t, 1> arrKeyIndices { 0 };
   static constexpr std::optional<std::size_t> optIdentityIndex { 0 };
   static constexpr std::array<std::size_t, 1> arrReadOnlyIndices { 4 };
};


class TTestDbNeu : public adecc::db::PersistentSystemData<testdbneu_list, TestDbNeuMetaData> {
public:
   using Base = adecc::db::PersistentSystemData<testdbneu_list, TestDbNeuMetaData>;
   using Base::Base;
   using Base::operator=;

   explicit TTestDbNeu(int const iId) {
	  Set<0>(iId);
	  }

   auto operator <=> (TTestDbNeu const& rhs) const {
	  return CompareSelected<0>(rhs.Data());
	  }

   bool operator == (TTestDbNeu const& rhs) const {
	  return EqualSelected<0>(rhs);
	  }

   auto const& Id() const { return Get<0>(); }
   auto const& Name() const { return Get<1>(); }
   auto const& Kommentar() const { return Get<2>(); }
   auto const& Wert() const { return Get<3>(); }
   auto const& WertDoppelt() const { return Get<4>(); }

   template <typename val_ty> requires std::assignable_from<element_ty<0>&, val_ty>
   void Id(val_ty&& theValue) { Set<0>(std::forward<val_ty>(theValue)); }

   template <typename val_ty> requires std::assignable_from<element_ty<1>&, val_ty>
   void Name(val_ty&& theValue) { Set<1>(std::forward<val_ty>(theValue)); }

   template <typename val_ty> requires std::assignable_from<element_ty<2>&, val_ty>
   void Kommentar(val_ty&& theValue) { Set<2>(std::forward<val_ty>(theValue)); }

   template <typename val_ty> requires std::assignable_from<element_ty<3>&, val_ty>
   void Wert(val_ty&& theValue) { Set<3>(std::forward<val_ty>(theValue)); }

   template <typename val_ty> requires std::assignable_from<element_ty<4>&, val_ty>
   void WertDoppelt(val_ty&& theValue) { Set<4>(std::forward<val_ty>(theValue)); }
};


using testdbneu_tuple_ty = typename TTestDbNeu::data_ty;


/*!
\brief Verifies SQL statements and output parameters generated by PersistentSystemData
\details
   The test verifies that identity and read-only fields do not occur in
   write SQL fragments while the data structure remains complete.

\param os Output stream for test messages
*/
void TestPersistentMetadata(std::ostringstream& os) {
   std::string const strInsertSql = TTestDbNeu::CreateInsertSql();
   std::string const strUpdateSql = TTestDbNeu::CreateUpdateSql();

   std::string const strExpectedInsertSql {
	  "INSERT INTO TestDbNeu (Name, Kommentar, Wert) "
	  "VALUES (:Name, :Kommentar, :Wert)"
	  };

   std::string const strExpectedUpdateSql {
	  "UPDATE TestDbNeu "
	  "SET Name = :Name, Kommentar = :Kommentar, Wert = :Wert "
	  "WHERE Id = :keyId"
	  };

   if (strInsertSql != strExpectedInsertSql) {
      throw std::runtime_error {
         std::format(
            "TestPersistentMetadata: INSERT SQL does not match.\nActual: {}\nExpected: {}",
            strInsertSql,
            strExpectedInsertSql
			)
         };
      }

   if (strUpdateSql != strExpectedUpdateSql) {
      throw std::runtime_error {
         std::format(
            "TestPersistentMetadata: UPDATE SQL does not match.\nActual: {}\nExpected: {}",
            strUpdateSql,
            strExpectedUpdateSql
            )
         };
      }

   auto vecInsertParams = TTestDbNeu::CreateInsertOutputParameters();
   auto vecUpdateParams = TTestDbNeu::CreateUpdateOutputParameters();

   if (vecInsertParams.size() != std::tuple_size_v<testdbneu_tuple_ty>) {
      throw std::runtime_error {
         "TestPersistentMetadata: INSERT output parameter count does not match"
         };
      }

   if (vecUpdateParams.size() != std::tuple_size_v<testdbneu_tuple_ty>) {
      throw std::runtime_error {
         "TestPersistentMetadata: UPDATE output parameter count does not match"
         };
      }

   auto const& [strInsertIdName, aInsertIdRole] = vecInsertParams[0];
   auto const& [strInsertReadonlyName, aInsertReadonlyRole] = vecInsertParams[4];

   if (strInsertIdName != "Id" ||
       aInsertIdRole != adecc::db_output_param_role::identity) {
      throw std::runtime_error {
         "TestPersistentMetadata: INSERT identity parameter is invalid"
         };
      }

   if (strInsertReadonlyName != "WertDoppelt" ||
       aInsertReadonlyRole != adecc::db_output_param_role::may_be_missing) {
      throw std::runtime_error {
         "TestPersistentMetadata: INSERT read-only parameter is invalid"
         };
      }

   auto const& [strUpdateKeyName, aUpdateKeyRole] = vecUpdateParams[0];
   auto const& [strUpdateReadonlyName, aUpdateReadonlyRole] = vecUpdateParams[4];

   if (strUpdateKeyName != "keyId" ||
       aUpdateKeyRole != adecc::db_output_param_role::key) {
      throw std::runtime_error {
         "TestPersistentMetadata: UPDATE key parameter is invalid"
         };
      }

   if (strUpdateReadonlyName != "WertDoppelt" ||
       aUpdateReadonlyRole != adecc::db_output_param_role::may_be_missing) {
      throw std::runtime_error {
         "TestPersistentMetadata: UPDATE read-only parameter is invalid"
         };
      }

   std::println(os, "PersistentSystemData metadata test passed.");
   std::println(os, "Insert SQL: {}", strInsertSql);
   std::println(os, "Update SQL: {}", strUpdateSql);
   }


/*!
\brief Drops and recreates the test table
\details
   The table contains an identity column and a computed read-only field.

\tparam app_db Logical database type
\param db Database
\param os Output stream for test messages
*/
template <adecc::db::logical_database_type app_db>
void CreatePersistentTestTable(app_db& db, std::ostringstream& os,
                               adecc::test::database_dialect const aDialect = adecc::test::database_dialect::sql_server) {
   db.ExecuteCommand(std::string{ adecc::test::PersistentTestTableDdl(aDialect) });
   std::println(os, "Table TestDbNeu was recreated for {}.", adecc::test::DialectName(aDialect));
   }


/*!
\brief Creates test objects following the PersistentSystemData pattern
\details
   The identity initially is 0. The read-only field remains \c std::nullopt
   because it must not be set by the client.

\returns Test data
*/
std::vector<TTestDbNeu> CreatePersistentInputRows() {
   std::vector<TTestDbNeu> vecRows;

   TTestDbNeu aAlpha;
   aAlpha.Id(0);
   aAlpha.Name("Alpha");
   aAlpha.Kommentar("Kommentar Alpha");
   aAlpha.Wert(10);
   aAlpha.WertDoppelt(std::nullopt);
   vecRows.emplace_back(aAlpha);

   TTestDbNeu aBeta;
   aBeta.Id(0);
   aBeta.Name("Beta");
   aBeta.Kommentar("Kommentar Beta");
   aBeta.Wert(20);
   aBeta.WertDoppelt(std::nullopt);
   vecRows.emplace_back(aBeta);

   TTestDbNeu aGamma;
   aGamma.Id(0);
   aGamma.Name("Gamma");
   aGamma.Kommentar("Kommentar Gamma");
   aGamma.Wert(30);
   aGamma.WertDoppelt(std::nullopt);
   vecRows.emplace_back(aGamma);

   return vecRows;
   }


/*!
\brief Converts PersistentSystemData objects into complete tuples
\details
   The tuples remain complete and positionally stable. No reduced
   INSERT or UPDATE tuple is created.

\param vecRows Domain test objects
\returns Complete tuple range
*/
std::vector<testdbneu_tuple_ty> ToTupleRange(
   std::vector<TTestDbNeu> const& vecRows
) {
   std::vector<testdbneu_tuple_ty> vecTuples;
   vecTuples.reserve(vecRows.size());

   for (auto const& aRow : vecRows) {
      vecTuples.emplace_back(aRow.Data());
      }

   return vecTuples;
   }


/*!
\brief Inserts test data using PersistentSystemData metadata
\details
   The INSERT uses OutputRange so that the generated identity is written
   back into the complete tuple.

\tparam app_db Logical database type
\param db Database
\param os Output stream for test messages
\returns Inserted tuples including generated identities
*/
template <adecc::db::logical_database_type app_db>
std::vector<testdbneu_tuple_ty> InsertPersistentRows(
   app_db& db,
   std::ostringstream& os
) {
   std::vector<TTestDbNeu> vecRows = CreatePersistentInputRows();
   std::vector<testdbneu_tuple_ty> vecInput = ToTupleRange(vecRows);

   auto aRange = db.template MakeOutputRange<
      int,
      std::string,
      std::string,
      int,
      std::optional<int>
   >(
      TTestDbNeu::CreateInsertSql(),
      TTestDbNeu::CreateInsertOutputParameters()
   );

   std::vector<testdbneu_tuple_ty> vecInserted;

   for (auto const& tupRow : aRange(vecInput)) {
      vecInserted.emplace_back(tupRow);
      }

   if (vecInserted.size() != vecInput.size()) {
      throw std::runtime_error {
         "InsertPersistentRows: number of inserted rows does not match"
         };
      }

   for (std::size_t uIndex{}; uIndex < vecInserted.size(); ++uIndex) {
      testdbneu_tuple_ty const& tupInput = vecInput[uIndex];
      testdbneu_tuple_ty const& tupOutput = vecInserted[uIndex];

      if (std::get<0>(tupOutput) <= 0) {
         throw std::runtime_error {
            "InsertPersistentRows: generated identity was not written back"
            };
         }

      if (std::get<1>(tupOutput) != std::get<1>(tupInput) ||
          std::get<2>(tupOutput) != std::get<2>(tupInput) ||
          std::get<3>(tupOutput) != std::get<3>(tupInput)) {
         throw std::runtime_error {
            "InsertPersistentRows: non-identity values changed unexpectedly"
            };
         }

      std::println(
         os,
         "Inserted: Id={}, Name={}, Comment={}, Value={}",
         std::get<0>(tupOutput),
         std::get<1>(tupOutput),
         std::get<2>(tupOutput),
         std::get<3>(tupOutput)
      );
      }

   return vecInserted;
   }


/*!
\brief Updates test data using PersistentSystemData metadata
\details
   The UPDATE uses OutputSink. Keys are bound using the \c key prefix;
   read-only fields remain in the complete tuple but do not occur in the SQL statement.

\tparam app_db Logical database type
\param db Database
\param vecInserted Inserted tuples including generated identities
\param os Output stream for test messages
*/
template <adecc::db::logical_database_type app_db>
void UpdatePersistentRows(app_db& db, std::vector<testdbneu_tuple_ty> const& vecInserted,
						  std::ostringstream& os) {
   if (vecInserted.size() < 3) {
	  throw std::runtime_error { "UpdatePersistentRows: too few inserted rows" };
	  }

   TTestDbNeu aAlpha;
   aAlpha = vecInserted[0];
   aAlpha.Name("Alpha update");
   aAlpha.Wert(110);

   TTestDbNeu aGamma;
   aGamma = vecInserted[2];
   aGamma.Name("Gamma update");
   aGamma.Wert(330);

   std::vector<TTestDbNeu> vecRows {  aAlpha, aGamma };

   std::vector<testdbneu_tuple_ty> vecUpdate = ToTupleRange(vecRows);

   auto aSink = db.template MakeOutputSink<int, std::string, std::string, int, std::optional<int>>(
											TTestDbNeu::CreateUpdateSql(),
											TTestDbNeu::CreateUpdateOutputParameters() );

   aSink = vecUpdate;

   for (auto const& tupRow : vecUpdate) {
	  std::println(
		 os,
		 "Updated: Id={}, Name={}, Value={}",
		 std::get<0>(tupRow),
		 std::get<1>(tupRow),
		 std::get<3>(tupRow)
	  );
	  }
   }


/*!
\brief Verifies the persisted data
\details
   The test verifies that updates were applied correctly and that the
   computed read-only field can be read from the database.

\tparam app_db Logical database type
\param db Database
\param os Output stream for test messages
*/
template <adecc::db::logical_database_type app_db>
void VerifyPersistentRows(app_db& db, std::ostringstream& os) {
   auto rngRows = db.template Execute<
      int,
      std::string,
      std::optional<std::string>,
      int,
      std::optional<int>
   >(
      TTestDbNeu::CreateSelectFromSql() + " order by Id"
   );

   std::vector<std::tuple<
      int,
      std::string,
      std::optional<std::string>,
      int,
      std::optional<int>
   >> vecRows;

   for (auto const& tupRow : rngRows) {
      vecRows.emplace_back(tupRow);
      }

   if (vecRows.size() != 3) {
      throw std::runtime_error {
         "VerifyPersistentRows: expected exactly three rows"
         };
      }

   if (std::get<1>(vecRows[0]) != "Alpha update" ||
       std::get<3>(vecRows[0]) != 110 ||
       !std::get<4>(vecRows[0]) ||
       *std::get<4>(vecRows[0]) != 220) {
      throw std::runtime_error {
         "VerifyPersistentRows: first row does not match"
         };
      }

   if (std::get<1>(vecRows[1]) != "Beta" ||
       std::get<3>(vecRows[1]) != 20 ||
       !std::get<4>(vecRows[1]) ||
       *std::get<4>(vecRows[1]) != 40) {
      throw std::runtime_error {
         "VerifyPersistentRows: second row does not match"
         };
      }

   if (std::get<1>(vecRows[2]) != "Gamma update" ||
       std::get<3>(vecRows[2]) != 330 ||
       !std::get<4>(vecRows[2]) ||
       *std::get<4>(vecRows[2]) != 660) {
      throw std::runtime_error {
         "VerifyPersistentRows: third row does not match"
         };
      }

   std::println(os, "VerifyPersistentRows: all checks passed.");

   for (auto const& [iId, strName, optKommentar, iWert, optWertDoppelt] : vecRows) {
      std::println(
         os,
         "Row: Id={}, Name={}, Comment={}, Value={}, WertDoppelt={}",
         iId,
         strName,
         optKommentar.value_or("<NULL>"),
         iWert,
         optWertDoppelt ? std::to_string(*optWertDoppelt) : "<NULL>"
      );
      }
   }


/*!
\brief Runs the complete PersistentSystemData test
\details
   The test follows the pattern used by domain PersistentSystemData classes:
   metadata, domain class, complete tuples, and persistence through OutputRange
   and OutputSink.

\tparam app_db Logical database type
\param db Database
\returns Test log
*/
template <adecc::db::logical_database_type app_db>
std::string RunPersistentSystemDataTests(app_db& db,
                                         adecc::test::database_dialect const aDialect = adecc::test::database_dialect::sql_server) {
   std::ostringstream os;

   auto aTransaction = db.Transaction();

   TestPersistentMetadata(os);

   CreatePersistentTestTable(db, os, aDialect);

   std::vector<testdbneu_tuple_ty> vecInserted =
	  InsertPersistentRows(db, os);

   UpdatePersistentRows(db, vecInserted, os);

   VerifyPersistentRows(db, os);

   aTransaction.CommitAndClose();

   std::println(os, "");
   std::println(os, "PersistentSystemData tests completed successfully.");

   return os.str();
   }

